### ISSUE TITLE
Edit/Delete micro-petition/petition not working

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#70]
1. go to http://localhost:8100/#/petition/145?focus=add-comment 
2. click Edit button
3. change text
4. submit fails with 

```
PUT https://api-dev.powerli.ne/api/micro-petitions/145 404 (Not Found)
```

the same for delete.

**Comment by petervojtek** [comment]
@igaponov , when I try to [delete micropetition](https://api-dev.powerli.ne/api-doc#delete--api-v2-micro-petitions-{id}), I make following request which fails with http status 500:

```
Request URL:https://api-dev.powerli.ne/api/v2/micro-petitions/145
Request Method:DELETE
Status Code:500 Internal Server Error
Remote Address:52.5.45.80:443

response:
{"code":500,"message":"Internal Server Error"}
```

Edit (PUT) works properly.

**Comment by jterps08** [comment]
Peter - Let me know if you are confused on the business logic. Otherwise, I think @habibillah may be able to help you with this. If he isn't responsive, please ask Igor.

**Comment by igaponov** [comment]
Fixed in https://github.com/PowerlineApp/powerline-server/pull/153

**Comment by petervojtek** [comment]
DELETE micro-petition still fails with error 500. Does this means that the [PowerlineApp/powerline-server#153](https://github.com/PowerlineApp/powerline-server/pull/153) is merged, but not deployed? If yes, how can I determine that a particular pull request has been actually deployed?

**Comment by igaponov** [comment]
You should ask @austinpapp . I think we need to some release log with current version's changes.

**Comment by petervojtek** [comment]
maybe we can do it this way:

the one who is assignee (owner) of an issue is the one, who is currently blocking it.
an example:
1. I start working on issue, I - Peter - am assignee.
2. I have some problem with backend, I ask Igor in comment, and change issue assignee to Igor
3. Igor will find out that he has to change some code on backend. He will do it, and change issue assignee to Austin, so that he knows he is blocking the issue
4. Austin will merge Igor's pull request and will change issue assignee to Peter, notifying me, that I can continue working on the bug.

**Comment by jterps08** [comment]
I do think that process makes a lot of sense to adopt, @petervojtek .... 

@austinpapp and @igaponov - can we adopt this 'assignee' approach Peter suggests above so we all know who is blocking progress on a bug at any given time?

**Comment by igaponov** [comment]
We can try

**Comment by austinpapp** [comment]
we can work with that. no problems.

**Comment by petervojtek** [comment]
ok, DELETE micropetition works now which indicates the backend changes has been deployed.

**Comment by jterps08** [comment]
Note: We will probably want to limit "Delete" ability to only micropetitions that have **not** been boosted in the future. I will create an independent issue for us to discuss this. 

Once a micropetition is boosted (it is sent to all members of the group), deleting a post could be problematic. If we were to allow an author to delete it, he could destroy an important ongoing conversation or he could 'bomb' the feed with his boosted posts only to delete them later. More exploration needed.
