### ISSUE TITLE
Unable to register user via email -- 500 internal error on backend

### ISSUE THREAD

**Issue by petervojtek** [PowerlineApp/powerline-mobile#82]
hi @igaponov , few days ago registration via email was working properly [since we resolved this bug](https://github.com/PowerlineApp/powerline-mobile/issues/60#issuecomment-227432232)

However today I tried to register new user and ended up with`500 Internal Server Error`. I made no changes to the registration code since the last bugfix..

```
Request URL:https://api-dev.powerli.ne/api/secure/registration
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:52.5.45.80:443

request headers:
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Content-Length:296
Content-Type:application/json
Host:api-dev.powerli.ne
Origin:http://localhost:8100
Referer:http://localhost:8100/
Token:null
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

request body:
{"first_name":"Peter6","last_name":"Peter6","username":"Peter6","password":"Peter6","confirm":"Peter6","address1":"Bucklin","city":"Bucklin","state":"KS","country":"US","zip":"67834","address2":"333","email":"peter6@test.com","email_confirm":"peter6@test.com","phone":"1234","birth":"01/01/1977"}

response:
{"code":500,"message":"Internal Server Error"}
```

**Comment by igaponov** [comment]
https://github.com/PowerlineApp/powerline-server/pull/156

**Comment by austinpapp** [comment]
fixed in powerlineapp/powerline-server#56 . please confirm this works.

**Comment by petervojtek** [comment]
still fails the same way:

```
Request URL:https://api-dev.powerli.ne/api/secure/registration
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:52.5.45.80:443


{"first_name":"Peter8","last_name":"Peter8","username":"Peter8","password":"Peter8","confirm":"Peter8","address1":"San Die","city":"San Diego","state":"CA","country":"US","zip":"11111","address2":"11","email":"peter8@test.com","email_confirm":"peter8@test.com","phone":"333","birth":"01/01/1977"}
Name

```

Actually the user is created (I can use his credentials to login).

**Comment by igaponov** [comment]
PowerlineApp/powerline-server#156 is not deployed yet

**Comment by jterps08** [comment]
Should be deployed now

**Comment by petervojtek** [comment]
I confirm it works now.

**Comment by austinpapp** [comment]
excellent. yup sorry for the delay on that fix. was testing some CI/CD stuff and this didnt get pushed out. thanks @jterps08
